
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author David
 */
public class VentanaRegitroPeriodista extends javax.swing.JFrame {

    private VentanaPeriodistas padre;

    public VentanaRegitroPeriodista() {
        initComponents();
    }

    public VentanaRegitroPeriodista(VentanaPeriodistas padre) {
        initComponents();
        this.padre = padre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonCerrarVentana = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        selectTipoPeriodista = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textFechaNacimiento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textCI = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        isEmpleado = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        textSueldo = new javax.swing.JTextField();
        labelDato1 = new javax.swing.JLabel();
        textDato1 = new javax.swing.JTextField();
        labelDato2 = new javax.swing.JLabel();
        textDato2 = new javax.swing.JTextField();
        botonRegistrarPeriodista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 52, 88));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRAR PERIODISTA");

        botonCerrarVentana.setText("X");
        botonCerrarVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarVentanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCerrarVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonCerrarVentana, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Forumulario de Registro Periodistas:");

        jPanel3.setLayout(new java.awt.GridLayout(9, 0, 5, 5));

        jLabel9.setText("Tipo Periodista:");
        jPanel3.add(jLabel9);

        selectTipoPeriodista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ConductorTV", "Escritor" }));
        selectTipoPeriodista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTipoPeriodistaActionPerformed(evt);
            }
        });
        jPanel3.add(selectTipoPeriodista);

        jLabel3.setText("Nombre:");
        jPanel3.add(jLabel3);
        jPanel3.add(textNombre);

        jLabel4.setText("Fecha Nacimiento:");
        jPanel3.add(jLabel4);
        jPanel3.add(textFechaNacimiento);

        jLabel5.setText("Cedula Identidad:");
        jPanel3.add(jLabel5);
        jPanel3.add(textCI);

        jLabel6.setText("Id Periodista:");
        jPanel3.add(jLabel6);
        jPanel3.add(textID);

        jLabel7.setText("Es empleado:");
        jPanel3.add(jLabel7);

        isEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        jPanel3.add(isEmpleado);

        jLabel8.setText("Sueldo:");
        jPanel3.add(jLabel8);
        jPanel3.add(textSueldo);

        labelDato1.setText("Casa Televisa:");
        jPanel3.add(labelDato1);
        jPanel3.add(textDato1);

        labelDato2.setText("Programa:");
        jPanel3.add(labelDato2);
        jPanel3.add(textDato2);

        botonRegistrarPeriodista.setText("Registrar Periodista");
        botonRegistrarPeriodista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarPeriodistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonRegistrarPeriodista, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonRegistrarPeriodista, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarVentanaActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_botonCerrarVentanaActionPerformed

    private void selectTipoPeriodistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTipoPeriodistaActionPerformed
        String tipoPeriodista = this.selectTipoPeriodista.getSelectedItem().toString();
        if (tipoPeriodista.equals("ConductorTV")) {
            this.labelDato1.setText("Casa Televisa:");
            this.labelDato2.setText("Programa:");
        } else {
            this.labelDato1.setText("Nombre Periodico:");
            this.labelDato2.setText("Sector:");
        }
    }//GEN-LAST:event_selectTipoPeriodistaActionPerformed

    private void botonRegistrarPeriodistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarPeriodistaActionPerformed
        String tipoPeriodista = this.selectTipoPeriodista.getSelectedItem().toString();
        String nombrePeriodista = this.textNombre.getText().toString();
        String fechaNacimieto = this.textFechaNacimiento.getText().toString();
        String cedulaIdentidad = this.textCI.getText().toString();
        String idPeriodista = this.textID.getText().toString();
        String isEmpleado = "true";
        if(this.isEmpleado.getSelectedItem().toString().equalsIgnoreCase("No")){
            isEmpleado = "false";
        } 
        String sueldoPeriodista = this.textSueldo.getText().toString();
        String dato1 = this.textDato1.getText().toString();
        String dato2 = this.textDato2.getText().toString();
        Periodista periodista = null;
        if (tipoPeriodista.equals("ConductorTV")) {
            ConductorTV conductorTV = new ConductorTV(
                    dato1,
                    dato2,
                    idPeriodista,
                    Boolean.valueOf(isEmpleado),
                    Double.parseDouble(sueldoPeriodista),
                    nombrePeriodista,
                    fechaNacimieto,
                    Integer.parseInt(cedulaIdentidad));
            periodista = conductorTV;
        } else {
            Escritor escritor = new Escritor(
                    dato1,
                    dato2,
                    idPeriodista,
                    Boolean.valueOf(isEmpleado),
                    Double.parseDouble(sueldoPeriodista),
                    nombrePeriodista,
                    fechaNacimieto,
                    Integer.parseInt(cedulaIdentidad));
            periodista = escritor;
        }
        padre.asociacionPeriodistas.agregarPeriodista(periodista);
        JOptionPane.showMessageDialog(this, "Periodista Registrado con Exito...!!!");
    }//GEN-LAST:event_botonRegistrarPeriodistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegitroPeriodista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegitroPeriodista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegitroPeriodista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegitroPeriodista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegitroPeriodista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrarVentana;
    private javax.swing.JButton botonRegistrarPeriodista;
    private javax.swing.JComboBox<String> isEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelDato1;
    private javax.swing.JLabel labelDato2;
    private javax.swing.JComboBox<String> selectTipoPeriodista;
    private javax.swing.JTextField textCI;
    private javax.swing.JTextField textDato1;
    private javax.swing.JTextField textDato2;
    private javax.swing.JTextField textFechaNacimiento;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textSueldo;
    // End of variables declaration//GEN-END:variables
}
